// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
import type { Metadata } from 'next';
import React from 'react';
import './globals.css';
import Header from '@/app/components/Header/Header';
import Footer from '@/app/components/Footer/Footer';

export const metadata: Metadata = {
  title: 'Куда съездить отдохнуть: блог о путешествиях',
  description:
    'Дневник странника – это блог о путешествиях. На сайте представлено описание культуры разных стран: вы узнаете, где отдохнуть летом, прочтете отзывы туристов об отелях, а также можете забронировать горящий тур.',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className="wrapper">
        <header>
          <Header />
        </header>
        <main> {children}</main>
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
